=== nbeaver/equajson/equajson-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "properties": {
        "copying": {
            "additionalProperties": false,
            "description": "Information on licensing and copyright.",
            "properties": {
                "authors": {
                    "description": "List of the people who wrote the JSON, not the equation itself.",
                    "items": {
                        "description": "Full name of person.",
                        "type": "string"
                    },
                    "type": "array"
                },
                "license-name": {
                    "description": "Usually a free software license, such as GPL, BSD, or MIT.",
                    "type": "string"
                },
                "license-url": {
                    "description": "Link to the text of the license, usually HTTP.",
                    "format": "uri",
                    "type": "string"
                },
                "year": {
                    "description": "Year the JSON was first written.",
                    "type": "integer"
                }
            },
            "required": [
                "authors",
                "license-name",
                "year"
            ],
            "type": "object"
        },
        "description": {
            "additionalProperties": false,
            "description": "Textual description of the equation.",
            "properties": {
                "terse": {
                    "description": "Description text that is 80 characters or less.",
                    "maxLength": 80,
                    "type": "string"
                },
                "verbose": {
                    "description": "The full text of the description. Don't add hard linebreaks; let the output formatter decide how to do that. Required field.",
                    "type": "string"
                }
            },
            "required": [
                "verbose"
            ],
            "type": "object"
        },
        "markup-languages": {
            "description": "Representation of the equation in various markup languages.",
            "additionalProperties": {
                "additionalItems": false,
                "description": "List of representations for a particular markup language, such as LaTeX.",
                "items": {
                    "additionalProperties": false,
                    "properties": {
                        "markup": {
                            "description": "The markup text for the equation.",
                            "type": "string"
                        },
                        "urls": {
                            "additionalItems": false,
                            "description": "Links to the markup text.",
                            "items": {
                                "description": "Actual URL, usually HTTP.",
                                "format": "uri",
                                "type": "string"
                            },
                            "type": "array"
                        }
                    },
                    "required": [
                        "markup"
                    ],
                    "type": "object"
                },
                "type": "array"
            },
            "type": "object"
        },
        "related-equations": {
            "description": "UUIDs of other equations that are related to this one.",
            "items": {
                "additionalProperties": false,
                "properties": {
                    "uuid": {
                        "description": "Universally unique identifier of related command.",
                        "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
                        "type": "string"
                    }
                },
                "required": [
                    "uuid"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "relevant-urls": {
            "description": "List of URLs that discuss the equation and its properties.",
            "items": {
                "additionalProperties": false,
                "minItems": 1,
                "properties": {
                    "date-known-good": {
                        "format": "date",
                        "type": "string"
                    },
                    "url": {
                        "format": "uri",
                        "type": "string"
                    }
                },
                "required": [
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "unicode-pretty-print": {
            "additionalProperties": false,
            "description": "Human-readable representation of the equations with Unicode text.",
            "properties": {
                "multiline" : {
                    "additionalItems": false,
                    "description": "An array of strings that show the equation two-dimensionally. Uses an array instead of a multiline string for portability reasons.",
                    "items": {
                        "description": "Horizontal slice of the equation.",
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array"
                },
                "one-line" : {
                    "description": "Textual representation of the equation on a single line. May contain many nested parentheses.",
                    "type": "string"
                },
                "parameters" : {
                    "description": "Descriptions and properties of the constants and variables in the equation. Must be an array to preserve order.",
                    "additionalItems": {
                        "additionalProperties": false,
                        "description": "The parameter.",
                        "properties": {
                            "always-an-integer": {
                                "description": "True if the quantity must be an integer or subset thereof such as a natural number.",
                                "type": "boolean"
                            },
                            "label": {
                                "description": "Short description of the quantity, suitable for an 'where x is the ...' type statement.",
                                "type": "string"
                            },
                            "dimensionless": {
                                "description": "True if the quantity is dimensionless.",
                                "type": "boolean"
                            },
                            "fixed-constant": {
                                "description": "True if the quantity has a fixed numeric value, such as π, √2, or the speed of light.",
                                "type": "boolean"
                            },
                            "symbol": {
                                "description": "The symbol for the quantity.",
                                "type": "string"
                            },
                            "urls":{
                                "additionalItems": false,
                                "description": "List of URLs directly about the quantity.",
                                "items": {
                                    "description": "The URL, usually HTTP.",
                                    "format": "uri",
                                    "type": "string"
                                },
                                "type": "array"
                            }
                        },
                        "type": "object"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            },
            "required": [
                "multiline",
                "one-line"
            ],
            "type": "object"
        },
        "uuid": {
            "description": "Universally Unique Identifier for this equation.",
            "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
            "type": "string"
        }
    },
    "required": [
        "description",
        "unicode-pretty-print",
        "uuid"
    ],
    "type": "object"
}

=== nbeaver/equajson/equajson/aab9ffc1-826c-416f-a62d-e5f3227d4ef2.json
{
    "copying": {
        "authors": [
            "Nathaniel Morck Beaver"
        ],
        "license-name": "MIT (Expat) License",
        "license-url": "http://opensource.org/licenses/MIT",
        "year": 2016
    },
    "description": {
        "terse": "Quadratic formula",
        "verbose": "Quadratic formula, the two solutions to the quadractic equation."
    },
    "markup-languages": {
        "AsciiMathML": [
            {
                "markup": "(-b +- sqrt(b^2 - 4a c)) / (2a)",
                "urls": [
                    "https://en.wikipedia.org/wiki/MathML#Example_and_comparison_to_other_formats"
                ]
            }
        ],
        "LaTeX": [
            {
                "markup": "$x = \\frac{ -b \\pm \\sqrt{b^2 - 4ac} }{2a}$",
                "urls": [
                    "https://en.wikipedia.org/wiki/MathML#Example_and_comparison_to_other_formats"
                ]
            }
        ],
        "LibreOffice Math": [
            {
                "markup" : "x = { -b +- sqrt {b^2 - 4ac} } over 2a",
                "urls": [
                    "https://en.wikipedia.org/wiki/MathML#Example_and_comparison_to_other_formats"
                ]
            },
            {
                "markup" : "x={-b ± sqrt {b^2 – 4ac}} over 2a",
                "urls": [
                    "https://en.wikipedia.org/wiki/MathML#Example_and_comparison_to_other_formats"
                ]
            },
            {
                "markup" : "x={-b plusminus sqrt {b^2 – 4 ac}} over {2 a}",
                "urls": [
                    "https://en.wikipedia.org/wiki/MathML#Example_and_comparison_to_other_formats"
                ]
            }
        ],
        "troff/eqn": [
            {
                "markup" : "x = {-b +- sqrt{b sup 2 – 4ac}} over 2a",
                "urls": [
                    "https://en.wikipedia.org/wiki/MathML#Example_and_comparison_to_other_formats"
                ]
            }
        ]
    },
    "relevant-urls": [
        {
            "date-known-good": "2016-02-14",
            "url": "http://mathworld.wolfram.com/QuadraticFormula.html"
        },
        {
            "date-known-good": "2016-02-14",
            "url": "http://planetmath.org/QuadraticFormula"
        },
        {
            "date-known-good": "2016-02-14",
            "url": "https://en.wikipedia.org/wiki/Quadratic_formula"
        }
    ],
    "unicode-pretty-print": {
        "multiline": [
            "            ______  ",
            "      −b ± √b²-4ac  ",
            "x =  ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒",
            "            2a      "
        ],
        "one-line": "x = (−b ± √b²-4ac)/(2a)",
        "parameters": [
            {
                "label": "quadratic coefficient",
                "dimensionless": true,
                "fixed-constant": false,
                "symbol": "a"
            },
            {
                "label": "linear coefficient",
                "dimensionless": true,
                "fixed-constant": false,
                "symbol": "b"
            },
            {
                "label": "constant coefficient",
                "dimensionless": true,
                "fixed-constant": false,
                "symbol": "c"
            },
            {
                "label": "variable",
                "dimensionless": true,
                "fixed-constant": false,
                "symbol": "x"
            }
        ]
    },
    "uuid": "aab9ffc1-826c-416f-a62d-e5f3227d4ef2"
}
